/*******************************************************************************
* FILENAME :        modules/def/dialogs.pwn
*
* DESCRIPTION :
*       Global constants of dialogs.
*
* NOTES :
*       -
*
*       Copyright Paradise Devs 2015.  All rights reserved.
*/

//------------------------------------------------------------------------------

enum
{
    DIALOG_HANDSHAKE_OFFER,
    DIALOG_HANDSHAKE_ACCEPT,

    DIALOG_KISS_OFFER,
    DIALOG_KISS_ACCEPT,

    DIALOG_BLOWJOB_OFFER,
    DIALOG_BLOWJOB_ACCEPT,

    DIALOG_BOXING_OFFER,
    DIALOG_BOXING_ACCEPT,

    DIALOG_LOGIN,
    DIALOG_REGISTER,
    DIALOG_REGISTER_AGE,
    DIALOG_REGISTER_NAME,
    DIALOG_REGISTER_EMAIL,
    DIALOG_REGISTER_GENDER,

    DIALOG_LOTTERY,

    DIALOG_PILOT_JOB,
    DIALOG_PILOT_SERVICES,

    DIALOG_TRUCK_JOB,
    DIALOG_TRUCKER_SERVICES,

    DIALOG_LUMBERJACK_JOB,
    DIALOG_LUMBER_SERVICES,

    DIALOG_PARAMEDIC_JOB,
    DIALOG_PARAMEDIC_SERVICES,


    DIALOG_NAVIGATOR_JOB,
    DIALOG_NAVIGATOR_SERVICES,

    DIALOG_GARBAGE_JOB,
    DIALOG_GARBAGE_SERVICES,

    DIALOG_FISHER_JOB,
    DIALOG_FISHER_SERVICES,

    DIALOG_TECHNICAL_JOB,
    DIALOG_TECHNICAL_SERVICES,

    DIALOG_BUSDRIVER_JOB,
    DIALOG_BUSDRIVER_SERVICES,

    DIALOG_PIZZA_JOB,

    DIALOG_DEALERSHIP,
    DIALOG_VEHICLE,

    DIALOG_GTA_MISSION,
    DIALOG_COLONEL_MISSION,

    DIALOG_PAINTBALL,
    DIALOG_PAINTBALL_RC,

    DIALOG_GPS,
    DIALOG_GPS_JOBS,
    DIALOG_GPS_INTEREST,
    DIALOG_GPS_BUSINESS,
    DIALOG_GPS_HOUSES,

    DIALOG_SHOOTING_RANGE,

    DIALOG_DRIVING_SCHOOL,

    DIALOG_FSTYLE,

    DIALOG_FACTION_INVITE,

    DIALOG_CHANGE_NAME,

    DIALOG_MESSAGE,

    DIALOG_AMMU,
    DIALOG_AMMU_AMMO,
    DIALOG_AMMU_GUNS,
    DIALOG_STORE,
	DIALOG_BURGER,
	DIALOG_CLUCKIN,
	DIALOG_PIZZA,
	DIALOG_DONUT,
	DIALOG_ADVERTISE,
	DIALOG_RESTAURANT,
	DIALOG_PHONE,
	DIALOG_BUY_CREDITS,
	DIALOG_CLUB,

    //
	DIALOG_ATTACHMENTS_CATEGORY,
	DIALOG_ATTACHMENTS_GLASSES,
	DIALOG_ATTACHMENTS_HATS,
	DIALOG_ATTACHMENTS_BANDANA,
	DIALOG_ATTACHMENTS_CAP,
	DIALOG_ATTACHMENTS_HELMETS,
	DIALOG_ATTACHMENTS_MASKS,
	DIALOG_ATTACHMENTS_EDIT,
	DIALOG_ATTACHMENTS_BONE,
	DIALOG_ATTACHMENTS_REMOVE,
	//

    DIALOG_LEAVE_JOB,

    //
    DIALOG_CHOOSE_GANGNAME
}
